apiVersion: 1

datasources:
  - name: PostgreSQL
    type: postgres
    access: proxy
    url: postgres:5432
    database: douyin_monitor
    user: douyin
    secureJsonData:
      password: douyin123
    jsonData:
      sslmode: disable
      postgresVersion: 1600
      timescaledb: false

  - name: InfluxDB
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    secureJsonData:
      token: douyin-token-123
    jsonData:
      version: Flux
      organization: douyin
      defaultBucket: douyin_data
      tlsSkipVerify: true